### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [jerrylee17/CMPE131G9_Inventory#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by jerrylee17** [comment]
Group #9 Class Section #1

**Comment by rickTaina** [comment]
This is Rick, Group 9.

**Comment by ericdou865** [comment]
Hello
- Eric D.

**Comment by cloud-oscar1** [comment]
Hello, 
This is Oscar.

**Comment by ProfRojas** [comment]
Thanks!
